table dim_vendedor
	lineageTag: aea8422a-48e9-4993-a198-945147b09ed8

	column id_vendedor
		dataType: int64
		formatString: 0
		lineageTag: fca5e379-b3bc-4aee-821d-67b1136ac78a
		summarizeBy: none
		sourceColumn: id_vendedor

		annotation SummarizationSetBy = Automatic

	column nombre_vendedor
		dataType: string
		lineageTag: 785b81b8-ac30-4090-84bd-3f56dff6e48f
		summarizeBy: none
		sourceColumn: nombre_vendedor

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 5b87f53c-13d4-4d35-a61e-04f8eaa20e01
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	partition dim_vendedor = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Juan Manuel\Documents\PERSONALES\PROYECTOS\Power-BI---analitica-retail-optica\data\raw\dim_vendedor.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_vendedor", Int64.Type}, {"nombre_vendedor", type text}, {"id_sede", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

